### ISSUE TITLE
Small issues with `eigen_decomposition_of_Hermitian_matrix.ipynb` notebook.

### ISSUE THREAD

**Issue by seberg** [BallisticLA/parla#4]
I was trying to run the `eigen_decomposition_of_Hermitian_matrix.ipynb` and ran into small technical issues.  Since notebooks are a bit weird with diffs, decided not to open a PR (but happy to do!).

* First import fails due to a missing `parla/tests/test_comps/__init__.py` (not sure if it should be added or the import removed though).   (EDIT: This might be a bit related to how I installed the package locally.)
* `from parla.drivers.evd import *` has to be "drivers" was `from parla.comps.evd import *` now
* The signatures changed, I modified them to (not quite sure that is correct):
   * `evd1(inner_num_pass=2, A=A0, k=target_rank, over=target_rank, tol=0.1, block_size=2, rng=123)`
   * `evd2(num_passes=3, A=A0, k=target_rank, over=target_rank, rng=123)`

At least on SciPy 1.8rc1 it may be that some of the `_` functions imported from scipy were renamed (or removed), that may need fixing, but Scipy 1.8 is not released yet so it doesn't matter.

**Comment by rileyjmurray** [comment]
Hi @seberg! Thanks so much for reporting this. We haven't done a good job of updating the notebooks as we've made changes to parla. I'll implement your suggested changes now.

**Comment by rileyjmurray** [comment]
@seberg these issues should be fixed. The notebook runs now, and I believe it runs correctly. I actually found (and fixed) a minor implementation error thanks to you reporting this issue!

I'll close this issue for now. Please feel free to post here again if it seems this isn't resolved.
